"""Summarize the pruning sweep after all 9 runs have completed.

Reads results/all_prune_metrics.csv (written incrementally by
eval_and_save_metrics.py) and produces:
  - a formatted table printed to stdout
  - prune_vs_accuracy.png
  - prune_vs_all_metrics.png (accuracy, precision, recall, F1, ROC-AUC)
  - metrics_table.txt (a LaTeX-ready tabular block)

Usage:
    python scripts/prune_sweep/plot_summary.py
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

SWEEP_DIR = Path(__file__).resolve().parent
RESULTS_DIR = SWEEP_DIR / "results"
CSV_PATH = RESULTS_DIR / "all_prune_metrics.csv"

TABLE_METRICS = ["accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc", "specificity", "balanced_accuracy"]
CHART_METRICS = ["accuracy", "precision", "recall", "f1", "roc_auc"]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Summarize prune-sweep results.")
    p.add_argument("--csv-path", type=Path, default=CSV_PATH)
    p.add_argument("--out-dir", type=Path, default=RESULTS_DIR)
    return p.parse_args()


def load_results(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(
            f"{csv_path} not found — run the sweep scripts first "
            f"(scripts/prune_sweep/generated_scripts/run_prune*.{{bat,sh}})."
        )
    df = pd.read_csv(csv_path)
    # If a percentage was re-run, keep only the latest row for that percent.
    df = df.drop_duplicates(subset="prune_percent", keep="last")
    df = df.sort_values("prune_percent").reset_index(drop=True)
    return df


def print_table(df: pd.DataFrame) -> None:
    cols = ["prune_percent"] + TABLE_METRICS
    print("\n" + "=" * 100)
    print("PRUNING SWEEP RESULTS")
    print("=" * 100)
    header = f"{'prune%':>8}" + "".join(f"{c:>14}" for c in TABLE_METRICS)
    print(header)
    print("-" * len(header))
    for _, row in df.iterrows():
        line = f"{row['prune_percent']:>8.0f}"
        for c in TABLE_METRICS:
            line += f"{row[c]:>14.4f}"
        print(line)
    print("=" * 100)


def plot_accuracy(df: pd.DataFrame, out_dir: Path) -> Path:
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(df["prune_percent"], df["accuracy"], marker="o", color="C0", linewidth=2)
    ax.set_xlabel("Pruning Percentage (%)")
    ax.set_ylabel("Accuracy")
    ax.set_title("Accuracy vs. Pruning Percentage")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    path = out_dir / "prune_vs_accuracy.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_all_metrics(df: pd.DataFrame, out_dir: Path) -> Path:
    fig, ax = plt.subplots(figsize=(9, 6))
    colors = ["C0", "C1", "C2", "C3", "C4"]
    for metric, color in zip(CHART_METRICS, colors):
        ax.plot(df["prune_percent"], df[metric], marker="o", label=metric, color=color, linewidth=2)
    ax.set_xlabel("Pruning Percentage (%)")
    ax.set_ylabel("Score")
    ax.set_title("Metrics vs. Pruning Percentage")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    path = out_dir / "prune_vs_all_metrics.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def write_latex_table(df: pd.DataFrame, out_dir: Path) -> Path:
    lines = []
    lines.append("% Auto-generated by scripts/prune_sweep/plot_summary.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{CT-ATPT performance across pruning percentages (held-out test set).}")
    lines.append("\\label{tab:prune_sweep}")
    ncols = 1 + len(TABLE_METRICS)
    lines.append("\\begin{tabular}{" + "c" * ncols + "}")
    lines.append("\\toprule")
    header_names = {
        "prune_percent": "Prune \\%",
        "accuracy": "Acc.",
        "precision": "Prec.",
        "recall": "Recall",
        "f1": "F1",
        "roc_auc": "ROC-AUC",
        "pr_auc": "PR-AUC",
        "specificity": "Spec.",
        "balanced_accuracy": "Bal. Acc.",
    }
    header_row = " & ".join([header_names["prune_percent"]] + [header_names[c] for c in TABLE_METRICS]) + " \\\\"
    lines.append(header_row)
    lines.append("\\midrule")
    for _, row in df.iterrows():
        cells = [f"{row['prune_percent']:.0f}"] + [f"{row[c]:.3f}" for c in TABLE_METRICS]
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    path = out_dir / "metrics_table.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    df = load_results(args.csv_path)
    print_table(df)

    acc_path = plot_accuracy(df, args.out_dir)
    all_path = plot_all_metrics(df, args.out_dir)
    table_path = write_latex_table(df, args.out_dir)

    print(f"\nWrote {acc_path}")
    print(f"Wrote {all_path}")
    print(f"Wrote {table_path}")


if __name__ == "__main__":
    main()
